import { chromium } from 'playwright';
const URL='https://clio.wd3.myworkdayjobs.com/en-US/ClioCareerSite/job/Graphic-Designer--5-Month-Contract-_REQ-5082';
async function openApplication(page){await page.goto(URL,{waitUntil:'domcontentloaded',timeout:60000});const a=page.locator('[data-automation-id="adventureButton"]');await a.waitFor({state:'visible',timeout:30000});console.log('JOB='+(await page.locator('[data-automation-id="jobPostingHeader"]').innerText()).trim());console.log('POSTED='+(await page.locator('[data-automation-id="postedOn"]').innerText()).replace(/\s+/g,' ').trim());await a.click();const m=page.getByRole('button',{name:/apply manually/i});await m.waitFor({state:'visible',timeout:15000});await m.click();await page.locator('#name--legalName--firstName').waitFor({state:'visible',timeout:30000});}
async function option(page,text){const esc=text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const x=page.locator('[role="option"]').filter({hasText:new RegExp(`^${esc}$`)}).last();await x.waitFor({state:'visible',timeout:12000});return x;}
async function clickOpt(page,text){const x=await option(page,text),p=x.locator('[data-automation-id="promptOption"]');if(await p.count())await p.click({force:true});else await x.click({force:true});await page.waitForTimeout(300);}
async function choose(page,aid,text){const b=page.locator(`[data-automation-id="${aid}"] button`).first();await b.click({force:true});await page.waitForTimeout(300);await clickOpt(page,text);}
async function core(page){const s=page.locator('#source--source');await s.click({force:true});await clickOpt(page,'Job Sites');await clickOpt(page,'Other');await s.press('Escape').catch(()=>{});await page.locator('#name--legalName--firstName').click({force:true});await choose(page,'formField-country','Canada');await page.locator('#name--legalName--firstName').fill('Prerna');await page.locator('#name--legalName--lastName').fill('Sharma');await page.locator('#address--city').fill('Toronto');await choose(page,'formField-countryRegion','Ontario');await page.locator('#emailAddress--emailAddress').fill('Visualartist.prerna@gmail.com');}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1600}});page.setDefaultTimeout(30000);await openApplication(page);await core(page);
const field=page.locator('[data-automation-id="formField-phoneType"]');const b=page.locator('#phoneNumber--phoneType');console.log('PHONE_FIELD_HTML='+(await field.evaluate(e=>e.outerHTML)).replace(/\s+/g,' ').slice(0,12000));console.log('BEFORE_BUTTON='+JSON.stringify(await b.evaluate(e=>({text:(e.innerText||'').trim(),aria:e.getAttribute('aria-label'),expanded:e.getAttribute('aria-expanded'),controls:e.getAttribute('aria-controls'),haspopup:e.getAttribute('aria-haspopup')}))));
await b.click();await page.waitForTimeout(700);console.log('AFTER_BUTTON='+JSON.stringify(await b.evaluate(e=>({text:(e.innerText||'').trim(),aria:e.getAttribute('aria-label'),expanded:e.getAttribute('aria-expanded'),controls:e.getAttribute('aria-controls'),haspopup:e.getAttribute('aria-haspopup')}))));
const popups=await page.locator('[role="listbox"], [role="menu"], [data-automation-id*="prompt"], [data-automation-id*="menu"]').evaluateAll(els=>els.filter(e=>{const r=e.getBoundingClientRect();const s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden';}).map((e,i)=>({i,tag:e.tagName,role:e.getAttribute('role'),aid:e.getAttribute('data-automation-id'),text:(e.innerText||e.textContent||'').trim().replace(/\s+/g,' ').slice(0,1200)})));
console.log('VISIBLE_POPUPS='+JSON.stringify(popups));console.log('BODY_TAIL='+(await page.locator('body').innerText()).replace(/\s+/g,' ').slice(-3000));await browser.close();})().catch(e=>{console.error(e.stack||e);process.exit(1)});
